server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.lq.springcloud.pojo  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
  application:
    name: provider #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01  # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848 #写localhost会报错
eureka:
  client:
    register-with-eureka: true #是否注册服务
    fetch-registry: true #服务是否可被发现
    service-url:
      defaultZone: http://localhost:6001/eureka/,http://localhost:6002/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port} #不显示主机名
    prefer-ip-address: true #访问路径显示ip地址